version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php_app
    restart: always
    working_dir: /var/www/html
    volumes:
      - D:/shopping-cart:/var/www/html
    env_file:
    - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - app_network

  nginx:
    image: nginx:latest
    container_name: nginx_server
    restart: always
    ports:
      - "8000:80"
    volumes:
      - D:/shopping-cart:/var/www/html
      - ./nginx/default.local.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
